app/routes.py
from flask import Blueprint
from app import db
from app.models import User, Todo
from flask import render_template, flash, redirect, url_for, request, jsonify
from flask_login import current_user, login_user, login_required, logout_user
from werkzeug.urls import url_parse
from app.forms import LoginForm, RegistrationForm, TodoForm
import uuid

site = Blueprint('Docket', __name__, )

@site.route('/')
def index():
    return render_template('index.html')

@site.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('Docket.todo'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('Docket.todo')
        return redirect(next_page)
    return render_template('login.html', form=form)


@site.route('/logout')
def logout():
    if current_user.is_authenticated:
        logout_user()
        return redirect(url_for('Docket.index'))
    return redirect(url_for('Docket.index'))


@site.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('Docket.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(api_token=str(uuid.uuid4()), username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Congratulations, you are now registered')
        return redirect(url_for('Docket.login'))
    return render_template('register.html', form=form)


@site.route('/todo')
def todo():
    if current_user.is_authenticated:
        form = TodoForm()
        todos = current_user.todos.order_by(Todo.timestamp.desc()).all()
        return render_template('todo.html', form=form, todos=todos)
    return redirect(url_for('Docket.index'))



@site.route('/newtodo', methods=['POST'])
def update():
    form = TodoForm()
    new_todo = Todo(body=form.todo.data, owner=current_user)
    db.session.add(new_todo)
    db.session.commit()
    todos = current_user.todos.order_by(Todo.timestamp.desc()).all()
    return render_template('todolist.html', todos=todos)


@login_required
@site.route('/deletetodo', methods=['POST'])
def delete():
    deleteid = request.form['id']
    Todo.query.filter_by(id=deleteid).delete()
    db.session.commit()
    todos = current_user.todos.order_by(Todo.timestamp.desc()).all()
    return render_template('todolist.html', todos=todos)


@site.route('/profile')
def profile():
    if current_user.is_authenticated:
        return render_template('profile.html', User=current_user)
    return redirect(url_for('Docket.index'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <link href="{{ url_for('static', filename='css/bootstrap.css') }}" rel="stylesheet">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        {% block title %}
        {% endblock %}
        {% block script %}
        {% endblock %}
    </head>
    <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <span class="navbar-brand">Docket</span>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('Docket.index') }}">Home</a>
                </li>
                {% if current_user.is_anonymous %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('Docket.login') }}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('Docket.register') }}">Register</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('Docket.profile') }}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('Docket.todo') }}">Todo</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('Docket.logout') }}">Logout</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="jumbotron">
        <div class="container text-center">
            {% block content %} {% endblock %}
        </div>
    </div>
    <div class="footer text-center">
        <p>Created by Kevin Tuck | Download the code <a href="https://github.com/keva161/Docket">here</a> | <a href="http://kevintuck.co.uk/">Visit my website</a> | Run into problems? Connect with me on <a href="http://twitter.com/keva161">Twitter</a>.</p>
    </div>
    </body>
</html>

app/templates/index.html
{%  extends "base.html" %}
{% block title %}
<title>Docket - Simple Todo application for you to practise your API testing</title>
{% endblock %}
{% block navbar %}
{% endblock %}
{% block content %}
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}
<div class="logo">
    <img src="/static/img/logo.png">
</div>
<div class="intro-text">
    <h4>Docket is fully fledged Todo web application for you to practise and learn about API testing.</h4>
</div>
<hr>
<div class="row justify-content-md-center">
    <div class="col-md-auto">
        <table class="table">
            <tbody>
            <tr>
                <td class="text-left"><p><strong>C</strong>reate new users and todo items</p></td>
            </tr>
            <tr>
                <td class="text-left"><p><strong>R</strong>ead your todo's via the web application and API protocol</p></td>
            </tr>
            <tr>
                <td class="text-left"><p><strong>U</strong>pdate your user details</p></td>
            </tr>
            <tr>
                <td class="text-left"><p><strong>D</strong>elete todo's and account from the database</p></td>
            </tr>
            </tbody>
        </table>
    </div>
    <div class="cta">
        <h5>Example Python API tests can be downloaded <a href="https://github.com/keva161/DocketTests">here</a></h5>
        <br>
        <p>The API is limited to 50 API calls per day and the application resets itself every 15 minutes. Please contact me if you need an extension. There are intended bugs, but please reach out if you are having issues!</p>
    </div>
</div>

{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% block title %}
<title>Docket - Login</title>
{% endblock %}
{% block content %}
<div class="row justify-content-md-center">
    <div class="col-md-auto">
        <div class="page-header">
            <h1>Sign in</h1>
            <small>Enter your details below to gain access to your todo list</small>
        </div>
        <hr>
        <form action="" method="post" novalidate>
            {{ form.hidden_tag() }}
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
            {% for error in form.username.errors %}
            <div id="error_message"><span style="color: red;">{{ error }}</span></div>
            {% endfor %}
            <div class="form-group">
                {{ form.username(class_="form-control") }}
            </div>
            <div class="form-group">
                {% for error in form.password.errors %}
                <div id="error"><span style="color: red;">{{ error }}</span></div>
                {% endfor %}
                {{ form.password(class_="form-control") }}
            </div>
            <div class="form-group">
                <div class="text-left">
                    {{ form.remember_me() }} {{ form.remember_me.label }}
                </div>
            </div>
                {{ form.submit(class_="btn btn-primary") }}
        </form>
    </div>
</div>
</body>
{% endblock %}

app/templates/profile.html
{%  extends "base.html" %}
{% block title %}
<title>Docket - Profile Page</title>
{% endblock %}
{% block navbar %}
{% endblock %}
{% block content %}
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-info alert-dismissible" role="alert">
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}
<div class="row justify-content-md-center">
    <div class="col-md-auto">
        <div id="profile_container">
            <table class="table">
                <tbody>
                <tr>
                    <th scope="row">Username</th>
                    <td>{{ User.username }}</td>
                </tr>
                <tr>
                    <th scope="row">Email</th>
                    <td>{{ User.email }}</td>
                </tr>
                <tr>
                    <th scope="row">API Token</th>
                    <td>{{ User.api_token }}</td>
                </tr>
                </tbody>
            </table>
            <p>Your API token can be used by placing <code>?token=...</code>in your header.</p>
            <p>Full API documentation can be read <a href="/api/documentation">here</a>.</p>
        </div>
    </div>
</div>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}
{% block title %}
<title>Docket - Registration Page</title>
{% endblock %}
{% block content %}
<div class="row justify-content-md-center">
    <div class="col-md-auto">
        <div class="page-header">
            <h1>Registration</h1>
            <small>To gain access to the application. Please enter your details below.</small>
        </div>
        <hr>
        <form action="" method="post">
            {{ form.hidden_tag() }}
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            {% for message in messages %}

            <div class="alert alert-info alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                {{ message }}
            </div>

            {% endfor %}
            {% endif %}
            {% endwith %}
            <div class="form-group">
                {{ form.username(class_="form-control") }}
                {% for error in form.username.errors %}
                <span style="color: red;">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.email(class_="form-control") }}
                {% for error in form.email.errors %}
                <span style="color: red;">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.password(class_="form-control") }}
                {% for error in form.password.errors %}
                <span style="color: red;">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.password2(class_="form-control") }}
                {% for error in form.password2.errors %}
                <span style="color: red;">{{ error }}</span>
                {% endfor %}
            </div>
            {{ form.submit(class_="btn btn-primary") }}
        </form>
    </div>
</div>
{% endblock %}

app/templates/todo.html
{%  extends "base.html" %}
{% block title %}
<title>Docket - Welcome</title>
{% endblock %}
{% block script %}
<script src="{{ url_for('static', filename='js/custom.js') }}"></script>
{% endblock %}

{% block content %}
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-success" role="alert">
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}
<div class="row justify-content-md-center">
    <div class="welcome col-md-auto">
        <strong><h1>Hello {{ current_user.username }}</h1></strong>
        <br>
        <h2>What do you need to do today?</h2>
        <br>
    </div>
</div>
<div class="row justify-content-md-center">
    <div class="col-md-auto">
        <form action="" method="post">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.todo (id="todoInput") }}
                <button class="btn btn-primary btn-sm updateButton">Add todo</button>
            </div>
        </form>
            <div id="todoList">
                <ul class="list-group">
                {% for todo in todos %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                    <div id="todoItem">{{ todo.body }}</div>
                        <button type="button" class="close" aria-label="Close"><span id="delete" class="{{ todo.id }}" aria-hidden="true">&times;</span></button>
                    </li>
                    {% endfor %}
                </ul>
            </div>
    </div>
</div>
{% endblock %}

app/templates/todolist.html
<ul class="list-group">
    {% for todo in todos %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
        <div id="todoItem">{{ todo.body }}</div>
        <button type="button" class="close" aria-label="Close"><span id="delete" class="{{ todo.id }}" aria-hidden="true">&times;</span></button>
    </li>
    {% endfor %}
</ul>